const Questions = [
  {
    id: "1",
    name: "leakage_awareness",
    question: "Do you ever experience any leakage of",
    type: "checkbox",
    options: ["urine", "gas", "stool"],
  },
  {
    id: "2",
    name: "urge_bathroom",
    question: "Do you ever have a sudden urge to run to the bathroom quickly to empty your",
    type: "checkbox",
    options: ["bladder", "bowels"],
  },
  {
    id: "3",
    name: "difficulty_emptying",
    question: "Do you ever experience pain or difficulty with emptying your",
    type: "checkbox",
    options: ["bladder", "bowels"],
  },
  {
    id: "4",
    name: "pain_using",
    question: "Do you ever have pain with using",
    type: "checkbox",
    options: ["a tampon", "a menstrual cup", "a pelvic exam", "sex"],
  },
  {
    id: "5",
    name: "pain_pressure",
    question: "Do you ever have any pain or pressure in your",
    type: "checkbox",
    options: ["abdomen", "low back", "pelvis", "tailbone"],
  },
  {
    id: "6",
    name: "pressure_heaviness",
    question: "Do you ever experience a feeling of pressure or heaviness in your",
    type: "checkbox",
    options: ["vagina", "anus"],
  },
  {
    id: "7",
    name: "bulging_tissue",
    question: "Do you ever notice a bulging of tissue at your",
    type: "checkbox",
    options: ["vagina", "anus"],
  },
  {
    id: "8",
    name: "vaginal_discharge",
    question:
      "Are you experiencing any abnormal vaginal discharge? (e.g., grey or yellow in color, clumpy/curd-like texture, or a fishy smell) Have you noticed a change in your discharge",
    type: "checkbox",
    options: ["volume", "color", "odor"],
  },
  {
    id: "9",
    name: "vaginal_vulvar",
    question: "Do you ever experience vaginal or vulvar",
    type: "checkbox",
    options: ["dryness", "burning", "itching"],
  },
  {
    id: "10",
    name: "changes_awareness",
    question: "Have you experienced changes in",
    type: "checkbox",
    options: [
      "clitoral sensation",
      "vulvar sensation",
      "vaginal sensation",
      "sexual arousal",
      "orgasm",
      "sex drive",
    ],
  },
  {
    id: "11",
    name: "conception_awareness",
    question: "Are you struggling with conception?",
    type: "radio",
    options: ["yes", "no"],
  },
  {
    id: "12",
    name: "period_frequency",
    question: "Are your periods",
    type: "checkbox",
    options: [
      "absent (no bleeding in a 90-day period)",
      "less than 21 days apart",
      "more than 35 days apart",
      "more than 7 days",
      "unpredictable",
      "painful",
    ],
  },
  {
    id: "13",
    name: "period_awareness",
    question: "Do you experience heavy bleeding with your periods that",
    type: "checkbox",
    options: [
      "soaks through one or more tampons or pads every hour for several hours and/or days in a row",
      "requires you to change tampons or pads during the night",
      "requires you to wear more than one pad at a time",
      "interferes with your quality of life",
    ],
  },
  {
    id: "14",
    name: "vaginal_awareness",
    question:
      "If you are in menopause (12 months of no periods, after your last menstrual period), have you experienced any new vaginal bleeding?",
    type: "radio",
    options: ["yes", "no"],
  },
  {
    id: "15",
    name: "hotflashes_awareness",
    question: "Do you experience hot flashes?",
    type: "radio",
    options: ["yes", "no"],
  },
  {
    id: "16",
    name: "sleep_awareness",
    question: "Do you experience sleep difficulties?",
    type: "radio",
    options: ["yes", "no"],
  },
  {
    id: "17",
    name: "headaches_awareness",
    question: "Do you experience headaches and/or migraines?",
    type: "radio",
    options: ["yes", "no"],
  },
  {
    id: "18",
    name: "mood_awareness",
    question: "Have you experienced any sudden or unexpected mood changes?",
    type: "radio",
    options: ["yes", "no"],
  },
  {
    id: "19",
    name: "breasts_awareness",
    question: "Have you noticed any new tenderness, swelling, lumps or bumps in your breasts?",
    type: "radio",
    options: ["yes", "no"],
  },
  {
    id: "20",
    name: "additional_comments",
    question: "Additional Comments",
    note: "Note: this checklist is intended to help with conversations with health professionals and not to be construed as medical advice or preference to any treatment. If there is anything else you’re experiencing that you would like to talk to a healthcare professional about, write it in the comment box below:",
    type: "text",
    options: [],
  },
];

export { Questions };
